export const Events = [{"Names":"Erste Musikinstrumente",
                        "Dates":"~32.000 v. Chr.",
                        "Explain":"Es ist eine Flöte aus Vogelknochen.",
                        'Explain2': 'Es ist eine Flöte aus dem Kochen eines Gänsegeiers. Sie wurde in der Höhle "Hoher Fels", ca. 20km westlich von Ulm, gefunden. Sie ist etwa 22cm lang und 8mm dick. Außerdem hat sie 5 Löcher, mit denen die Tonhöhe verändert werden kann. Demnach waren auch komplexere Melodien möglich. Auch das Anblas-Ende ist in Form eines V. Man vermutet, dass Musik dazu beigetragen haben kann, größere soziale Netzwerke zu bilden.'}, 
                        {"Names":"Erste Haustiere der Menschen",
                        "Dates":"13000 v. Chr.",
                        "Explain":"Die ersten Haustiere sind Wölfe. Mit der Zeit werden sie immer zahmer und zu Hunden."}, 
                        {"Names":"Beginn Mittelsteinzeit",
                        "Dates":"~9600 v. Chr.",
                        "Explain":"Man nennt die Mittelsteinzeit fachsprachlich „Mesolithikum“."}, 
                        {"Names":"Erste Bauern in Mitteleuropa",
                        "Dates":"5500 v. Chr.",
                        "Explain":"Sie kommen aus dem Norden Griechenlands und der Türkei."}, 
                        {"Names":"Beginn der Jungsteinzeit",
                        "Dates":"~5000 v. Chr.",
                        "Explain":"Man nennt die Jungsteinzeit in der Fachsprache „Neolithikum“."}, 
                        {"Names":"Tod von Ötzi",
                        "Dates":"~3300 v. Chr.",
                        "Explain":"Seine Mumie wird jedoch erst 1991 von Wanderern in den Ötztaler Alpen gefunden."}, 
                        {"Names":"Beginn der ägyptischen Hochkultur",
                        "Dates":"3000 v. Chr.",
                        "Explain":"Man nennt das alte Ägypten auch „Kemet“. Übersetzt heißt das „Schwarzes Land“."}, 
                        {"Names":"Erste Kämpfe der Ägypter gegen andere Dörfer",
                        "Dates":"~2800 v. Chr.",
                        "Explain":"Die ägyptischen Soldaten sind mit Booten über den Nil gefahren, um nubische Dörfer anzugreifen."}, 
                        {"Names":"Fertigstellung der Stufenpyramide von Sakkara",
                        "Dates":"2650 v. Chr.",
                        "Explain":"Gebaut für König Djoser ist sie die älteste Pyramide. Zuerst sollte sie jedoch keine Pyramide werden, sondern eine Mastaba (eine Art Plattform). Später wurde sie durch Hinzufügen mehrerer Schichten zur Pyramide. "}, 
                        {"Names":"Baubeginn der Cheops-Pyramide",
                        "Dates":"2560 v. Chr.",
                        "Explain":"Die Cheops-Pyramide ist die größte und älteste der drei Pyramiden von Gizeh. Sie gilt als eines der sieben Weltwunder der Antike."}, 
                        {"Names":"Entstehung der Statue „Sabu und seine Frau Meretites“",
                        "Dates":"2400 v. Chr.",
                        "Explain":"Es handelt sich um eine Sitzstatue. Sabu ist der Vorsteher der Balsamierer."}, 
                        {"Names":"Ende der Steinzeit",
                        "Dates":"2200 v. Chr.",
                        "Explain":"Die Steinzeit bezeichnet man als früheste Epoche der Menschheit."}, 
                        {'Names':'Der älteste Epos der Menschheit wird aufgeschrieben', 
                        'Dates':'~2100 v. Chr.', 
                        'Explain':'Es handelt sich um die Geschichte des Babylonischen Königs Gilgamesch und seinen besten Freund Enkidu. Es wurde um ~2100 v. Chr. nur angefangen ihn aufzuschreiben und wurde viele Jahrhunderte mündlich Überliefert',
                        'Explain2': 'Der Epos wurde anfangs nur mündlich überliefert und mit der Zeit langsam aufgeschrieben. Ca. 2100 v. Chr. wurden die ersten Teile in Steintafeln gemeißelt, der größte Teil stammt jedoch wahrscheinlich von Sin-leqe-unnini, der um 1100 v. Chr. das Epos auf 12 Tontafeln zusammengefasst hat. ' + '<br>' + '-' + '<br>' + 'In dem Epos geht es um einen alten, mesopotanischen König namens Gilgamesch. Dieser soll zu zwei Drittel Gott sein und glaub sich als gutaussehender König alles erlauben zu können. So zwingt er seine Leute zu Fronarbeit, wodurch viele ihre Familie nicht mehr sehen können. Daraufhin erschafft die Schöpfergöttin Aruru aus Lehm einen Mann namens Enkidu. Dieser war riesengroß, am ganzen Körper behaart und lebt zusammen mit den Tieren. ' + '<br>' + '-' + '<br>' + 'Eines Tages erblickt ihn ein Jäger, welcher sich erstmal fürchtete. Nach einigen Tagen, in denen Enkidu immer wieder die Fallen des Jägers zerstörte, wird der Jäger wütend. Man bringt Enkidu die üppige Dirne Schamchat um ihn in die Gemeinschaft einzugliedern. Nachdem sie ihn ihre Brüste zeigt kann er nicht widerstehen. Sie schlafen sechs Tage und sieben Nächte miteinander. Die wilden Tiere liefen danach von Enkidu weg, weshalb er mit Schamchat nach Uruk, dem Königreich Gilgameschs, zurückkehrt. Er will sich mit Gilgamesch anfreunden, damit dieser ein besserer König wird. ' + '<br>' + '-' + '<br>' + 'Währenddessen hatte Gilgamesch zwei Träume: In einem ist ein Meteor vom Himmel gefallen, worum sich alle versammelt haben. In dem anderen liegt auf den Straßen von Uruk eine Axt, zu der viele Leute hinrennen. Er hebt beides hoch und legt sie seiner Mutter, Ninsun, vor die Füße. Er berichtet seiner weisen Mutter von den Träumen, und diese sagt ihm vorraus, dass er einen starken Freund bekommen wird, dessen Auswirkung auf Gilgamesch gewaltig wird.' + '<br>' + '-' + '<br>' + 'In einem Hirtenlager in der Nähe trinkt Enkidu währenddessen Bier und isst Brot. Anfangs hatte er noch großes Misstrauen, jedoch verschwand das nach einiger Zeit, weshalb er auch begann laut zu singen. Am nächsten Tag erfährt Enkidu von einem Mann auf dem Weg zur Hochzeit, dass Gilgamesch sein Recht, zuerst mit der Braut zu schlafen, nutzen will. Dieser will das nicht zulassen, weshalb er vor den Ort der Hochzeit geht und Gilgamesch zu einem Kampf herrausfordert. So kommt es auch, so dass die Stadtmauern vom Impakt des Kampfes erzittern. Nach einer Weile geht Gilgameschs Mutter, Ninsun, dazwischen. Daraufhin geben sich die beiden die Hände. Gilgamesch schlägt Enkidu vor, dass die beiden zum Zedernwald gehen, um den Wächter des Waldes, den Chumbaba, zu töten. Enkidu hat Angst davor. Er hörte von einem schrecklichen Gott in dem dunklen Wald, weshalb er vermutet auf einem Schlag zu erlahmen. Gilgamesch aber meint, dass der Mensch, weil er so vergänglich ist, sich mit Heldentaten einen Namen machen muss. Enkidu gibt dem nach und willigt ein.' + '<br>' + '-' + '<br>' +'Die Beiden geben bei den Waffenschmieden Kampfgeräte in Auftrag: Ihre Äxte und Schwerter sollen jeweils sieben Talente wiegen und ihre Gürtel ein Talent. Die Ältesten Zweifeln am Sinn der Expedition, geben letzten Endes jedoch dem König nach. Vor der Abreise befragt Ninsun nocheinmal das Orakel. Sie vollzieht rituelle Waschungen und zieht ihren wertvollsten Schmuck an, um auf dem Dach des Tempels zum Sonnengott Schamasch zu beten. Dieser soll Gilgamesch tagsüber beschützen und nachts unter den Schutz der Sterne stellen. Am nächsten Tag beginnen die beiden ihre Reise.' + '<br>' + '-' + '<br>' + 'Sie kommen schnell vorran. In nur drei Tagen überwinden sie einen Weg von für gewöhnlich eineinhalb Monaten. Am Tagesende errichtet Enkidu jedes Mal ein Traumhaus und Gilgamesch bringt auf Bergen ein Mehlopfer dar. Gilgamesch hat insgesamt fünf Träume. Beim ersten stürzt ein Berg auf ihn, worauf darunter ein strahlender König hervorzieht. Enkidu denkt, dass der Berg den Chumbaba repräsentiert und der König Schamasch, Gilgameschs Retter. In den anderen vier Träumen jedoch versagen die beiden auf ihrer Reise. Nach einer Weile dauert Schamasch die Reise zu lange und wird ungeduldig. Vom Himmel aus ruft er den beiden zu, dass der Chumbaba sechs seiner sieben schützenden Gewänder abgelegt hat. Sie sollen sofort angreifen.' + '<br>' + '-' + '<br>' + 'Gilgamesch und Enkidu stehen vor den unglaublich hohen Zedern und dem Zedernberg, die Wohnung der Götter. Sie schreiten vorran, bis sie auf den Chumbaba treffen. Dieser beschimpfte Enkidu, indem er ihn die Ausgeburt einer Sumpf- und Wasserschildkröte, die keine Muttermilch trank, nennt. Er tritt heftig auf den Boden, sodass sich die Erde spaltet und zu hohen Gebirgen auftürmt. Von den hohen Gebirgen fallen Felsbrocken nieder, mit denen die beiden erstmal zu tun hatten. Daraufhin schickt Schamasch ein gewaltiges Unwetter mit 13 Winden, mit denen er den Chumbaba aufhällt. Dieser ist Gilgameschs Waffen schutzlos ausgeliefert. Er fleht die beiden an, sein Leben zu verschonen, doch sie wollen nur seinen Tod und den damit einhergehenden Ruhm. Der Chumbaba richtet sich auf und verflucht sie: "Nicht sollen die beiden alt werden!" brüllt er. Gilgamesch spaltet mit seinem Schwert seinen Nacken und Enkidu reißt ihm seine Lungen raus. Nach dem Kampf fallen sie hinab in die Bäume. Die beiden zimmern aus einer besonders hohen Zeder ein gewaltiges Tor für den Tempel von Nippur, bauen ein Floß und transportieren es auf dem Fluss Euphrat in die Stadt.' + '<br>' + '-' + '<br>' + 'In Uruk angekommen wäscht Gilgamesch sein verfilztes Haar und setzt sich seine Krone auf. Nach einiger Zeit, und wahrscheinlich durch seine Heldentat, wird die Göttin Ishtar auf seine Schönheit aufmerksam. Sie verspricht ihn alles: Sämtliche Reichtümer, Streitwagen aus Gold, viele Schafe und Ziegen, er soll sie jedoch heiraten. Gilgamesch lehnt das vorzügliche Angebot ab und beschimpft sie daraufhin. Ishtar lässt sich das gar nicht gefallen, sie kocht vor Wut und bittet ihren Vater, Anu, den Himmelsstier auf Gilgamesch loszulassen. Ishtar erhält von ihrem Vater sein Leitseil und führt ihn zur Erde. Dort angekommen trocknet der Forst durch seine bloße Anwesenheit aus und der Flusswasserspiegel sinkt. Sein Schnauben erzeugt so gewaltige Gruben, dass 200 Männer aus Uruk dort hineinfallen. Enkidu jedoch, der weit größer als alle anderen war, versinkt gerade mal bis zu den Hüften. Er springt heraus und packt den Stier an den Hörnern. Dieser versucht sich zu wehren, jedoch fasst Enkidu den Stier am Schwanz und stellt einen Fuß auf sein Hinterteil. Diese Zeit nutzt Gilgamesch, um dem Tier das Herz auszuschneiden. Dieses opfert er Schamasch.' + '<br>' + '-' + '<br>' + 'In der nächsten Nacht erwacht Enkidu aus einem Traum. Darin hat die Götterversammlung ihn und Gilgamesch wegen dem töten des Chumbaba und dem Himmelsstier zum Tote verurteilt. Dem Götterkönig Enlil zufolge soll jedoch nur Enkidu sterben. Daraufhin wird das Tor, welches die beiden gebaut haben, verflucht, um seinen Untergang zu beschwichtigen. Gilgamesch will sie umstimmen. Er verspricht sie anzubeten, ihnen eine Goldstatue von Enkidu zu opfern, jedoch vergeblich. Enkidu selbst hat sich bereits aufgegeben, da es nichts nütze, gegen das Schicksal anzukämpfen. Gilgamesch wird wütend: "Der Jäger ist schuld, und die Dirne, die Enkidu von den Tieren weggezerrt hat. Wäre all das nicht passiert, hätte er jetzt nicht sterben müssen. Warum nur..." Schamasch versucht Gilgamesch zu beruhigen. Es war doch erst die Tat dieser beiden, die Enkidu zu ihm geführt hätte. Nach zwölf Tagen ruft Enkidu Gilgamesch zu seinem Sterbebett. "Ich konnte mich doch nicht mit Heldentaten bekannt machen. Es tut mir leid, Gilgamesch", beklagt er zu seinem einzigen Freund, und stirbt.' + '<br>' + '-' + '<br>' + 'Nach dem Tot seines besten Freundes ist Gilgamesch am Boden zerstört. Er errichtet eine prächtige Ruhestätte für Enkidu. Damit diese vor Grabräubern sicher ist, wird der Fluss "Euphrat" vorrübergehend umgelenkt, damit sie im Flussbett errichtet werden kann. Aufgrund seiner tiefen Trauer bleibt Gilgameschs Haar verfilzt. Mit einem Löwenfell bekleidet durchquert er die Steppe bis zum Zwillingsgebirge, die Grenze zum Ende der Welt. Dort erwarten ihn zwei Skorpionsmenschen. Sie fragen ihm, warum er hergekommen ist. Gilgamesch meint, er will seinen Vorfahren Uta-napischti suchen, dem die Götter die Unsterblichkeit schenkten. Von ihm wollte er wissen, wie man den Tot überwindet. Die Skorbionsmenschen wundern sich kurz, da es niemand wagt den weg zu gehen, lassen ihn aber durch.' + '<br>' + '-' + '<br>' + 'Gilgamesch geht durch einen Weg, in dem zwölf Meilen an Finsternis herrscht. Er war kurz vor dem Aufgeben, bis er am Ende Licht sah. Dort war ein Wald, in dem Edelsteine an den Bäumen hingen. Dort an einem Meeresufer angekommen wird er von der Schankwirtin Siduri gesichtet. So verwildert wie Gilgamesch aussah, bekam sie erstmal Angst, verriegelte die Tür und ging aufs Dach. Da berichtete Gilgamesch von seinen und Enkidus Heldentaten, von seinem Tod, wie sehr er Enkidu liebte und wie sehr er ihn betrauerte. Und auch von der plötzlichen Angst seines Endes. Auf die Frage, wie er zu Uta-napischti gelangt, rät Siduri von der Reise ab, da nur Schamasch das Meer je überquerte. Er soll nicht von Tod weglaufen. Jedoch verweist sie ihn auf den Schiffer Ur-schanabi, welcher mit den Steinernden, Steinwesen, denen das Wasser vom Fluss des Totes nichts anhat, Bäume fällt. Gilgamesch überwältigt den Fährmann und zerschmettert die Steinernden. Da nur diese den Fluss überlebten, muss Gilgamesch 300 Bäume fällen und daraus 30m lange Stangen herstellen. Er darf jede Stange nur einmal abstoßen, da er sonst stirbt. Nachdem die letzte Stange kurz vor seinem Ziel verbraucht war, nutzte er seine Kleidung als Segel, um den Rest zu überwinden.' + '<br>' + '-' + '<br>' + 'Dort findet er Uta-napischi. Dieser hört Gilgamesch an, will ihm jedoch nicht helfen, da er ein guter König auf Erden sein' +
                        ' soll. Doch Gilgamesch will unbedingt wissen, wieso Uta-napischti unsterblich ist. Dieser erzählt Gilgamesch von der Sinflut. Seinerzeit schickten die Götter eine große Flut über die Erde. Der Gott Ea, Fürst der Weisheit, sagte Uta-napischti, er soll eine große Arche bauen. Mit einem versprechen von reichhaltiger Ernte lockte er Menschen aller Art auf das Schiff. Er lud es komplett voll mit Menschen, Vieh und Reichtümern. Daraufhin tobte ein starker Sturm, der alles was lebte unter sich begrub. Am siebten Tage war es still. Auf der Suche nach Land sah er zwölf Inseln. Er legte am Berg Nimusch an und ließ eine Taube und Schwalbe fliegen, welche beide zurückkahmen. Ein Rabe jedoch kehrte nicht zurück. Darauf lockte er die Götter mit einem Opfer an. Enlil, welcher die Flut schickte, wurde wegen der Überlebenden wütend. Ea konnte ihn jedoch beruhigen, er hätte Hunger und Krankheiten schicken sollen, anstatt alle zu vernichten. Jetzt soll er den Überlebenden helfen. Wieder bei Sinnen schenkte Enlil Uta-napischti und seiner Frau für ihre Dienste die Unsterblichkeit und machte sie zu Göttern.' + '<br>' + '-' + '<br>' + 'Uta-napischti will wissen, durch welche große Tat Gilgamesch unter den Göttern aufgenommen werden soll. Was hat er vollbracht. Er soll zur Probe sieben Tage lang wachen. Gilgamesch jedoch schläft sechs Tage und sieben Nächte wie ein Stein. Er hat nicht bestanden und muss zu den Lebenden zurückkehren. Uta-napischti erzählt ihm jedoch noch von einer Stachelpflanze, die ewiges Leben schenken soll. Um an diese Pflanze zu kommen bindet Gilgamesch Steine an seine Füße, damit er an den Boden des Apsu, ein unterirdischer Süßwasserozean, gelangt. Dort pflückt er die Pflanze. Er will die Wirkung der Pflanze an einem Alten in Uruk erproben. Auf dem Rückweg kommt er an einem Brunnen vorbei und badet darin. Da kommt eine Schlange angekrochen und nimmt die Pflanze mit. Daraufhin häutet sich diese: Deshab können Schangen sich auch ab sofort häuten und ihre Jugend beibehalten. Gilgamesch bricht zu Boden: Alles, die gesamte Reise, war umsonst. Er kehrt mit Ur-schanabi, dem Fährmann, nach Uruk zurück. Doch war die Reise wirklich umsonst? Gilgamesch lernte, das er, statt unsterblich zu werden, ein großer König für sein Volk sein soll und durch seine Taten unsterblich werden soll. Er zeigt Ur-schanabi die prächtige Stadt. Daraufhin lässt er große Bauwerke in Auftrag geben, darunter eine riesige Mauer, die Uruk auch Jahrhunderte nach seinem Tod noch beschützen soll.'},
                        {"Names":"Entstehung des ägyptischen „Totenbuchs“",
                        "Dates":"1500 v. Chr.",
                        "Explain":"Im Totenbuch befindet sich eine Sammlung von Beschwörungsformeln, Zaubersprüchen und Anweisungen."}, 
                        {"Names":"Beginn der Herrschaft von Thutmosis III.",
                        "Dates":"1479 v. Chr.",
                        "Explain":"Da er bei seiner Thronbesteigung noch ein Kind ist, übernimmt seine Stiefmutter Hatschepsut die Regierungsgeschäfte."}, 
                        {"Names":"Vollendung des Deir el-Bahari",
                        "Dates":"~1468 v. Chr.",
                        "Explain":"Der Toten- und Göttertempel Deir el-Bahari ist unter Hatschepsut entstanden. Das in ca. 20 Jahren erbaute Gebäude gilt als architektonisches Meisterwerk."}, 
                        {"Names":"Ende von Hatschepsuts Regierung",
                        "Dates":"~1458 v. Chr.",
                        "Explain":"Die Dauer ihrer Herrschaft wird von 1479 v. Chr. bis 1458 v. Chr. geschätzt."}, 
                        {"Names":"Entstehung der Wandmalerei „Bestrafung eines Bauern“",
                        "Dates":"1375 v. Chr.",
                        "Explain":"Auf dem Gemälde ist die Bestrafung eines Bauern zu sehen, der seine Steuern nicht gezahlt hat."}, 
                        {"Names":"Entstehung der Kalksteinbüste der Nofretete",
                        "Dates":"1350 v. Chr.",
                        "Explain":"Die Büste gilt als bekanntester Kunstschatz aus dem alten Ägypten. Trotz ihres Alters ist die Büste noch gut erhalten."}, 
                        {"Names":"Ende der Regierung von Tutanchamun",
                        "Dates":"1323 v. Chr.",
                        "Explain":"Sein Grab wird 1922 im Tal der Könige gefunden. Es ist noch komplett erhalten."}, 
                        {"Names":"Herrschaft von Ramses II.",
                        "Dates":"Ab 1279 v. Chr.",
                        "Explain":"Während seiner Zeit als Pharao schließt er Frieden mit den ehemaligen Feinden der Ägypter, den Hethitern."}, 
                        {"Names":"Die mythische Gründung Roms",
                        "Dates":"753 v. Chr",
                        "Explain":"Das Datum gilt als die Grundlage der römischen Zeitrechnung."}, 
                        {"Names":"Beginn der römischen Republik",
                        "Dates":"510 v. Chr.",
                        "Explain":"Nach der Vertreibung der etruskischen Könige. Bye bye, Monarchie. Hallo, Republik!"}, 
                        {'Names': 'Das Dyonysos-Theater wird errichtet',
                        'Dates': '~500 v. Chr.',
                        'Explain': 'Der Gang ins Theater ist für die alten Griechen eine bürgerliche Pflicht: Wer sich den Eintritt nicht leisten kann wird von der Polis (Stadt) unterstützt'},
                        {"Names":"Die Plebejer (nicht Patrizier) erkämpfen sich Rechte.",
                        "Dates":"ab 500 v. Chr.",
                        "Explain":"Kurze Zusammenfassung des Events: Die Plebejer erledigen die blöden Arbeiten, haben nicht mal die Chance, durch Heirat aufzusteigen und haben kaum Rechte. Folge: nachvollziehbare Unzufriedenheit und letztlich die Ständekämpfe"}, 
                        {"Names":"Ende der ägyptischen Hochkultur",
                        "Dates":"300 v. Chr.",
                        "Explain":"Eine andere Bezeichnung für Ägypten ist „Ta meri“, was übersetzt „geliebtes Land“ heißt."}, 
                        {"Names":"Erste Provinz im Imperium Romanum",
                        "Dates":"~ 264 v. Chr.",
                        "Explain":"Die Römer haben sich Sizilien geschnappt. Sie werden in ihrer Laufzeit weitere 39 Provinzen einkassieren."}, 
                        {"Names":"Entstehung des „Steins von Rosette“",
                        "Dates":"196 v. Chr.",
                        "Explain":"Auf dem Stein befindet sich der gleiche Text in drei verschiedenen Sprachen(u.a. Altgriechisch). So konnte man die Hieroglyphen entschlüsseln."}, 
                        {"Names":"Alle freien Bürger Italiens werden römische Bürger.",
                        "Dates":"89 v. Chr.",
                        "Explain":"Anfangs bekommen nur Bürger von latinischen Städten das Bürgerrecht zugeschrieben. Das ändert sich nun."}, 
                        {"Names":"Der größte Sklavenaufstand der Antike",
                        "Dates":"73 v. Chr.",
                        "Explain":"70000 Sklaven ziehen unter dem Gladiatorsklaven Spartacus los, um für bessere Lebensbedingungen zu kämpfen. Der Aufstand wird niedergeschlagen."}, 
                        {'Names': 'Der Mechanismus von Antikythera wird gebaut',
                        'Dates': '~70 v. Chr.',
                        'Explain': 'Es handelt sich um einen antiken, analogen Computer um die Sonnen- und Mondlaufbahn sowie Finsternisse vorherzusagen. Wahrscheinlich waren auch noch 5 Planeten eingetragen.'},
                        {"Names":"Ausruf Caesars zum Diktator auf Lebenszeit",
                        "Dates":"44 v. Chr.",
                        "Explain":"Caesar lässt sich 44 v. Chr. vom Senat zum Diktator auf Lebenszeit ausrufen. Seine Regierung unter diesem Titel dauert nicht allzu lang an."}, 
                        {"Names":"Caesars Ermordung",
                        "Dates":"44 v. Chr.",
                        "Explain":"An den Iden des März wird Caesars Ermordung vollzogen. 60 Personen sind beteiligt, jedoch erleidet Caesar „nur“ 23 Stichwunden."}, 
                        {"Names":"Octavian als „erster Mann im Staat“, also als „Princeps“",
                        "Dates":"31. v. Chr.",
                        "Explain":"Octavian (besser bekannt unter seinem Ehrentitel „Augustus“) gilt als erster römischer Kaiser. Er bezeichnet sich jedoch nicht als solchen. Er hat wohl nicht wie sein Vorgänger enden wollen."}, 
                        {"Names":"Caesars Sohn heißt ab jetzt Augustus",
                        "Dates":"27 v. Chr.",
                        "Explain":"Octavian, der Adoptivsohn Caesars, nennt sich nun „Augustus“ , nachdem er den Tod seines Vaters gerächt hat."}, 
                        {"Names":"Zeitalter des Augustus",
                        "Dates":"um Christi Geburt",
                        "Explain":"Auch das „Goldene Zeitalter“ genannt, da Augustus seinen Job als Herrscher herausragend erledigt."}, 
                        {"Names":"Caligula wird zum Kaiser gekrönt",
                        "Dates":"37 n. Chr.",
                        "Explain":"Caligula ist der wohl verrückteste Kaiser der Römer. Er ernannte sein Pferd zum Konsul, ernannte sich zum Gott und erklärte angeblich Neptun den Krieg. Er wurde nach nur 4 Jahren ermordet."}, 
                        {"Names":"Brand Roms",
                        "Dates":"64 n. Chr.",
                        "Explain":"In Neros Regierungszeit findet der größte Brand in der Geschichte Roms statt. Die Voraussetzungen für die Katastrophe sind gewesen: engstehende Häuser, Hochsommer, starker Wind."}, 
                        {"Names":"Titus und Vespian zerstören das religiöse Zentrum der Juden, den Tempel in Jerusalem",
                        "Dates":"70 n. Chr.",
                        "Explain":"Die Kriegsbeute hat den Bau des Kolosseums finanziert."}, 
                        {"Names":"Einweihung des Kolosseums in Rom",
                        "Dates":"80 n. Chr.",
                        "Explain":"Der Eintritt zum Kolosseum ist für die freien Bürger Roms kostenlos. "}, 
                        {"Names":"Baubeginn des Limes auf germanischem Gebiet",
                        "Dates":"~ 100 n. Chr.",
                        "Explain":"Das 550 km lange Konstrukt wird aus Palisaden (Baumstämmen) und vereinzelt aus Mauergliedern gebaut. Ganze zwei Jahrhunderte ist der Limes in Gebrauch."}, 
                        {"Names":"Größte Ausdehnung des Römischen Reiches",
                        "Dates":"117 n. Chr.",
                        "Explain":"Mit 60 Mio. Einwohnern und 40 Provinzen erreicht Rom seine größte Ausdehnung. (Hättet ihr zu der Zeit im Mittelmeerraum Urlaub machen wollen, dann solltet ihr besser Latein können.)"}, 
                        {"Names":"Bau der Porta Nigra in Trier",
                        "Dates":"170 n. Chr.",
                        "Explain":"Es ist ein Gebäude mit sehr schöner Aussicht und vielen Treppenstufen."}, 
                        {"Names":"Das Christentum wird zur Staatsreligion in Rom",
                        "Dates":"um 380 n. Chr.",
                        "Explain":"Kaiser Theodosius verbietet darauf sogar nichtchristliche Feste, wie die olympischen Spiele."}, 
                        {"Names":"Ende der römischen Kaiserzeit im Westen",
                        "Dates":"476 n. Chr.",
                        "Explain":"Ende mit der Niederlage gegen Sultan Mehmed II., der Konstantinopel erobert."}, 
                        {'Names': 'Errichtung der Aachner Königspfalz durch Karl dem Großen',
                        'Dates': 'ab 780 n. Chr.',
                        'Explain': 'Er hat durch den Ausbau das Ziel, ein "neues Rom" nördlich der Alpen zu errichten'},
                        {"Names":"Kaiserkrönung Karls des Großen",
                        "Dates":"800 n. Chr.",
                        "Explain":"Karl bekommt vom Papst ein Banner der Stadt Rom und den Schlüssel zum Grab des hl. Petrus geschenkt."}, 
                        {"Names":"Der Zerfall des Fränkischen Reiches",
                        "Dates":"um 850 n. Chr.",
                        "Explain":"Nach dem Tod von Ludwig der Frommen (840). Die Nachfolger stritten um das Erbe. Teilung in Frankreich, Italien und das “Deutsche Reich”."}, 
                        {"Names":"Krönung Ottos I. zum König der Franken",
                        "Dates":"936 n. Chr. ",
                        "Explain":"In der Aachner Pfalz wird er, nach dem Tod seines Vaters (König Heinrich I.) zum König der Franken gekrönt."}, 
                        {"Names":"Kaiserkrönung von Otto I. der Große",
                        "Dates":"962 n. Chr.",
                        "Explain":"der Kaiser soll der Kirche bei der Erneuerung des westlichen Kaisertums helfen (Verteidigung und Verbreitung des Christentums)"}, 
                        {"Names":"Die Machtübernahme des ersten Kaisers der Song Dynastie",
                        "Dates":"970 n. Chr.",
                        "Explain":"Die Zeitepochen Chinas werden in die Dynastien des aktuell regierenden Stammes eingeteilt. Die Song-Dynastie löst ein Zeitalter wirtschaftlichen Aufschwungs aus.,"},
                        {"Names":"Der erste Europäer lässt sich in Grönland nieder",
                        "Dates":"982 n. Chr",
                        "Explain":"Nachdem Erik der Rote für drei Jahre aus Island verbannt wurde, segelt er in ein Land im Westen, welches zuvor gesichtet worden ist, um seine Verbannung dort abzusitzen."}, 
                        {"Names":"Entdeckung Amerikas durch den ersten Europäer",
                        "Dates":"um 1000 n. Chr.",
                        "Explain":"Der Wikinger Leif Eriksson entdeckt auf seiner Rückreise nach Grönland ein unbekanntes Land. Nach einer weiteren Expedition dahin erkundet er weitere Gebiete der nordamerikanischen Küste."}, 
                        {"Names":"Schlacht von Hasting",
                        "Dates":"1066 n. Chr.",
                        "Explain":"Die französischen Normannen trafen wegen schlechtem Wind bei der Schlacht zu spät ein. In dem Zeitpunkt wurde England im Norden angegriffen und die Armee war erschöpft"}, 
                        {"Names":"Die Muslime besiegten die Byzantiner in der Schlacht von Manzikert",
                        "Dates":"1071 n. Chr.",
                        "Explain":"1071 n. Chr. wurden die Byzantiner aus Kleinasien verdrängt und die Pilgerwege nach Jerusalem unterbrochen; darauf bat der byzantinische Kaiser den Papst in Rom um Hilfe"}, 
                        {"Names":"Gang nach Canossa",
                        "Dates":"1076n. Chr.",
                        "Explain":"Dies beschreibt den Bitt- und Bußgang des römisch-deutschen Kaiser Heinrich IV., der in Folge des Investiturstreites exkommuniziert wird."}, 
                        {"Names":"Die Kreuzzüge starten",
                        "Dates":"1095 n. Chr.",
                        "Explain":"religiös und wirtschaftlich motivierte Kriege der Kirche gegen vor allem muslimische Staaten im Nahen Osten"}, 
                        {"Names":"Erstmals große Übergriffe gegen die jüdische Bevölkerung im Zusammenhang mit den Kreuzzügen.",
                        "Dates":"1096 n. Chr.",
                        "Explain":"Als „Feinde Christi” bezeichnet, werden sie geplündert, vertrieben und getötet."}, 
                        {"Names":"Jerusalem wird durch die Kreuzfahrer im ersten Kreuzzug erobert.",
                        "Dates":"1099n. Chr.",
                        "Explain":"Dabei kommt es zur Belagerung, Plünderung und Ermordung von Muslimen und Juden durch Christen. So wird aus der Wallfahrt ein Eroberungskrieg."}, 
                        {"Names":"Verfassung des Wormser Konkordates",
                        "Dates":"1122 n. Chr.",
                        "Explain":"Konfliktlösung zum Investiturstreit zwischen Kaiser und Papst."}, 
                        {"Names":"Ein Staufer wird erstmals zum römisch-deutschen König gewählt",
                        "Dates":"um 1138 n. Chr.",
                        "Explain":"Damit beginnt eine kulturellen Blüte (Dichter, Musiker, Turniere) an den Höfen der Adligen."}, 
                        {"Names":"Raschid ad-Din Sinan übernimmt die Führung der Assassinen in Syrien",
                        "Dates":"um 1162 n. Chr.",
                        "Explain":"Er wird auch „Der alte vom Berge“ genannt. Die Attentäter der Assassinen schlugen meist auf öffentlichen Plätzen zu und sahen ihr Leben als unwichtig an"}, 
                        {"Names":"Mainzer Hoffest (zum Höhepunkt der Stauferzeit)",
                        "Dates":"1184 n. Chr.",
                        "Explain":"Gastgeber: Kaiser Friedrich I. (Barbarossa). Aus dem ganzen Reich kommen ca. 70 000 Menschen aus den unterschiedlichsten Schichten."}, 
                        {"Names":"Zurückeroberung Jerusalems durch Sultan Saladin",
                        "Dates":"1187 n. Chr.",
                        "Explain":"Die Stadt wird belagert. Nach 12 Tagen kommt es zu einer friedlichen Übergabe der Stadt."}, 
                        {"Names":"Die Inkas gründen die Stadt Cusco",
                        "Dates":"Um 1200 n. Chr. ",
                        "Explain":"Mit der Gründung der Stadt beginnt eine Herrschafts-periode der Inkas. Die Stadt ist in zwei Stadthälften gegliedert."}, 
                        {"Names":"Der Aufstieg des mongolischen Reichs zu einer Weltmacht",
                        "Dates":"Ab 1206 n. Chr.",
                        "Explain":"Unter Dschingis Khan erobern die Mongolen weite Gebiete des asiatischen Raums. Nach seinem Tod im Jahr 1260 zerbricht es wieder unter seinen Erben."}, 
                        {"Names":"Die Magna Charta wird unterzeichnet",
                        "Dates":"1215 n. Chr.",
                        "Explain":"Brief zur verfassungsmäßigen Regierung von England, wodurch die Macht des Königs beschränkt wird."}, 
                        {"Names":"Das „Statut zugunsten der Fürsten“ wird aufgestellt",
                        "Dates":"1232 n. Chr.",
                        "Explain":"Seit dem 13. Jh. vergrößern die Fürsten ihre Macht Schritt für Schritt auf Kosten des Königs und anderer Grundherren. Dieses Gesetz ist ein Beispiel dafür."}, 
                        {"Names":"Gründung des Osmanischen Reiches",
                        "Dates":"1299n. Chr.",
                        "Explain":"Gründung unter Sultan Osman I. Er verdrängt das byzantinische Reich aus Kleinasien."}, 
                        {'Names': 'Generalstände in Frankreich erhalten das Recht, Könige zu beraten und außerordentliche Steuern zu bewilligen',
                        'Dates': '1302 n. Chr.',
                        'Explain': 'Die Generständeversammlung wird meist in Krisenzeiten vom König wegen neuen Steuern oder riskanten Verträgen einberufen. Sie besteht aus Adel, Klerus und dem dritten Stand'},
                        {"Names":"Veröffentlichung von Dantes Werk „Göttliche Komödie“",
                        "Dates":"1321 n. Chr.",
                        "Explain":"Das Werk definiert die Hölle grundsätzlich neu. Es führte das Italienische als Literatursprache ein."}, 
                        {"Names":"Höhepunkt der Pestwelle in Europa",
                        "Dates":"um 1349 n. Chr.",
                        "Explain":"Ausgelöst durch unhygienische Verhältnisse. Juden gelten als Sündenböcke."}, 
                        {"Names":"Die Goldene Bulle wird verfasst.",
                        "Dates":"1356 n. Chr.",
                        "Explain":"Es wird unter Kaiser Karl IV. und den Kurfürsten in Nürnberg verfasst. Dadurch wird die Wahlordnung der Könige festgelegt, die noch bis 1806 gültig ist."}, 
                        {"Names":"Der Buchdruck mit beweglichen Lettern wird erfunden",
                        "Dates":"um 1450 n. Chr.",
                        "Explain":"Nach mehreren Versuchen schafft es Johann Gutenberg endlich den Buchdruck zu revolutionieren. Eines der ersten gedruckten Bücher ist die Bibel."}, 
                        {"Names":"Geburt Leonardo da Vincis",
                        "Dates":"1452 n. Chr.",
                        "Explain":"Er wird in Anchiano bei Vinci als Sohn eines Notars geboren."}, 
                        {"Names":"Eroberung Konstantinopel durch das Osmanische Reich",
                        "Dates":"1453 n. Chr",
                        "Explain":"Durch seine Artillerie Einheiten eroberte Mehmed II. die Hauptstadt des byzantinischen Reiches am 29. Mai 1453. Danach wurde er Muhamed der Eroberer genannt."}, 
                        {"Names":"Beginn der Sengoku-Zeit in Japan",
                        "Dates":"1477 n. Chr.",
                        "Explain":"Innerhalb dieser Zeit kämpfen etwa 200 Reiche um die Vormacht in Japan. Aufgrund der andauernden Kämpfe ist jedoch nicht viel über diese Zeit bekannt"}, 
                        {"Names":"Der erste Seeweg nach Indien über Afrika wird gefunden",
                        "Dates":"1488 n. Chr.",
                        "Explain":"Nachdem Konstantinopel erobert wurde, kontrollierten die Muslime die Handelswege nach Asien. Deswegen suchten die Staaten anderen Wege."}, 
                        {"Names":"Entdeckung Amerikas durch Christoph Kolumbus",
                        "Dates":"1492 n. Chr.",
                        "Explain":"Um einen kürzeren Handelsweg nach Indien zu finden, sucht Kolumbus einen Weg um den Globus."}, 
                        {"Names":"Die Mona Lisa wird gemalt",
                        "Dates":"1503 n. Chr.",
                        "Explain":"Der Maler des Gemäldes ist Leonardo da Vinci. Die darauf abgebildete Person ist unbekannt."}, 
                        {"Names":"Luther veröffentlicht seine 95 Thesen gegen die Kirche",
                        "Dates":"31. Oktober 1517",
                        "Explain":"Ob Luther die Thesen wirklich an die Tür der Schlosskirche Wittenberg genagelt hat, ist umstritten."}, 
                        {"Names":"Der Spanier Franzisco Pizzaro erobert das Reich der Inkas",
                        "Dates":"1533 n. Chr.",
                        "Explain":"Er nutzt den Bürgerkrieg zwischen den Brüdern Atahualpa und Huáscar aus, um das Reich zu erobern."}, 
                        {'Names': 'Die Gründung der Englischen Kirche (church of england)',
                        'Dates': '1534 n. Chr.',
                        'Explain': 'Da sich der König wegen der katholischen Kirche nich von seiner Frau trennen kann, um Anne Boleyn zu heiraten, spaltet er die Kirche von Rom ab'},
                        {'Names': 'Kurfürst Maximilian I. wird Herrscher von Bayern', 
                        'Dates': '1597 n. Chr.', 
                        'Explain': 'Durch die Ausschaltung der ständischen Mitwirkungsrechte errichtet er ein absolutistischen Regierungssystem in Bayern'},
                        {"Names":"Der Beginn des 30-jährigen Kriegs",
                        "Dates":"1618 n. Chr.",
                        "Explain":"Er bestand aus mehreren Kriegszügen, die mit modernen Feuerwaffen und schweren Kanonen ausgeführt wurden"},
                        {'Names': 'Ursprüngliche Errichtung des Jagdschlosses Versailles', 
                        'Dates': '1623 n. Chr.', 
                        'Explain': "Ludwig XIII. errichtet das Schloss um sich von seinen Pflichtern und seiner Mutter Maria de' Medici zu entfliehen. Es diente ihn als Unterkunft für seine Jagdausflüge"},
                        {'Names': 'Ludwig XIV. wird König von Frankreich', 
                        'Dates': '1643 n. Chr.', 
                        'Explain': 'Er ist zu dem Zeitpunkt gerade mal vier Jahre alt'},
                        {'Names': 'Umzug des frz. Königs und der Regierung ins Schloss von Versailles', 
                        'Dates': '1682 n. Chr.', 
                        'Explain': 'Das Schloss von Versailles ist seit 1979 Weltkulturerbe'}, 
                        {'Names': 'Heirat von Kurfürst Max II. Emanuel von Bayern und der Kaisertochter Maria Antonia von Österreich', 
                        'Dates': '1685 n. Chr.',
                        'Explain': 'Er erhält dadurch Anspruch auf das riesige Erbe der spanischen Habsburger'},
                        {'Names': 'Schlacht bei Höchstädt',
                        'Dates': '13. August 1704',
                        'Explain': 'Die Schlacht bringt die entscheidente Wende im spanischen Erbfolgekrieg zugunsten des habsburgerischen Kaisers gegen die Franzosen'},
                        {'Names': 'Die erste nutzbare Dampfmaschine wird erfunden',
                        'Dates': '1712 n. Chr.',
                        'Explain': 'Thomas Newomen entwirft sie. Er kann damit mit einer Wasserpumpe das Wasser aus Bergwerken abpumpen'},
                        {'Names': 'Baubeginn der Residenz in Würzburg',
                        'Dates': '1720 n. Chr.',
                        'Explain': 'Die Residenz wird im 2. Weltkrieg schwer beschädigt'},
                        {'Names': 'Tod des bayrischen Kurfürsten Max II. Emanuel',
                        'Dates': '1726 n. Chr.',
                        'Explain': 'Er hinterlässt Schulden, zu deren Tilgung das bayrische Volk über hundert Jahre brauchen sollte'},
                        {'Names': 'James Watt revolutioniert die Dampfmaschine',
                        'Dates': '1769 n. Chr.',
                        'Explain': 'Sie funktioniert über einen Wasserkessel, ein Ventil, einen Kolben und eine Übersetzung der Vor- und Rückwärtsbewegung'},
                        {'Names': 'Die 13 amerikanischen Kolonien erkären ihre Unabhängigkeit von Großbritannien',
                        'Dates': '4. Juli 1776',
                        'Explain': 'Das war der Beginn der USA und gilt heute noch als nationaler Feiertag. Damit beginnen die amerikanischen Unabhängigkeitskriege.'},
                        {'Names': 'Frankreich tritt dem amerikanischen Unabhängigkeitskrieg bei',
                        'Dates': '1778 n. Chr.',
                        'Explain': 'Frankreich sieht darin eine Chance die Seemacht Großbritannien stark zu schwächen und selbst außenpolitische Anerkennung zu erhalten'},
                        {'Names': 'Der Sturm auf die Bastille', 
                        'Dates': '14. Juli 1789', 
                        'Explain': 'Die Bastille, eine königliche Festung und Symbol der Unterdrückung, wird von einer Menschenmenge belagert und eingenommen. Dieses Ereignis gilt als Beginn der französichen Revolution'},
                        {'Names': 'Der Rheinbund wird gegründet',
                        'Dates': '1806 n. Chr.',
                        'Explain': 'Napoleon gründet diesen nach seinem Europa Feldzug zwangsweise mit 16 Fürsten. Dadurch verpflichten sich diese, Napoleon im Kriegsfall zu unterstützen.'},
                        {'Names': 'Napoleon beginnt seinen Russlandfeldzug',
                        'Dates': '1812 n. Chr.',
                        'Explain': 'Dazu nutzt er die Soldaten die er durch den Rheinbund erhalten hat. Napoleon verliert schließlich durch einen taktischen Rückzug der Russen in Kombination mit dem kalten Klima.'},
                        {'Names': 'Der Rheinbund wird aufgelöst',
                        'Dates': '19. Oktober 1813',
                        'Explain': 'Nach Frankreichs fehlgeschlagenen Russlandfeldzug verbünden sich viele deutsche Länder, um sich gegen das geschwächte Frankreich zu wehren. Die entscheidente Niederlage Frankreichs war in der Völkerschlacht von Leipzig.'},
                        {'Names': 'Der Wiener Kongress kommt zu einem Ende',
                        'Dates': '9. Juni 1815',
                        'Explain': 'Das zentrale Ergebnis des Kongress ist der deutsche Bund. Weil niemand seine Macht verlieren will, soll das ehemalige Reich in den Fürstentümern gespalten bleiben'},
                        {'Names': 'Napoleon wird entgültig besiegt',
                        'Dates': '18. Juli 1815',
                        'Explain': 'Nachdem er aus dem Exil zurückgekommen ist verbünden sich Großbritannien, Russland, Österreich und Preußen erneut. Der entscheidente Sieg war am 18. Juli 1815 in der Schlacht bei Waterloo'},
                        {'Names': 'Die erste öffentliche Eisenbahn wird eingeweiht',
                        'Dates': '27. September 1825',
                        'Explain': 'Die 39 Kilometer lange Stecke führt vom englischen Stockton nach Darlington '},
                        {'Names': 'Das erste beständige Foto wird aufgenommen',
                        'Dates': '1826 n. Chr.',
                        'Explain': 'Joseph Nicéphore Niépce kann über 8 Stunden den Ausblick seines Arbeitszimmers auf eine mit Asphalt beschichtete Zinnblatte ablichten.'},
                        {'Names': 'Das Hambacher Fest beginnt', 
                        'Dates': '27. Mai 1832',
                        'Explain': 'Darin entladet sich der Wunsch der Bevölkerung auf eine geeinte Republik. Der deutsche Bund reagiert darauf mit verschärften Maßnahmen zur Unterdrückung der Freiheitsbewegung.'},
                        {'Names': 'Die Märzrevolution in Europa beginnt',
                        'Dates': 'März 1848',
                        'Explain': 'Nach der Februarrevolution in Paris breitete sich eine Aufbruchstimmung in Europa aus. Die Interessen sind je nach Region unterschiedlich, doch alle forderten eine Änderung des aktuellen Systems'},
                        {'Names': 'Der amerikanische Bürgerkrieg beginnt',
                        'Dates': 'Dezember 1860',
                        'Explain': 'Eine zentrale Frage war die Sklaverei: Die nördischen Staaten sind dagegen, da sie nicht mit dem Gleichheitsgebot im Einklang war. Die südlichen Staaten brauchen sie jedoch, da ihre Plantagen darauf basieren'},
                        {'Names': 'Der Preußisch-deutsche Krieg beginnt',
                        'Dates': '14. Juni 1866',
                        'Explain': 'Nachdem Preußen die Gastreiner Konvention gebrochen hat, stimmen die restlichen Staaten Österreichs Mobilisierung des Bundesheers zu. Dadurch beginnt Preußens Krieg gegen den deutschen Bund'},
                        {'Names': 'Das Radar wird erfunden',
                        'Dates': '30. April 1904',
                        'Explain':"Christian Hülsmeyer erstellt auf Basis der Hertz'schen Spiegelversuchen ein Gerät, um die Laufzeit von reflektierten Wellen zu messen"},
                        {'Names': 'Der erste Balkankrieg beginnt',
                        'Dates': '8. Oktober 1912',
                        'Explain': 'Die kombinierten Armeen der Balkanstaaten überwanden die anfangs zahlenmäßig minderwertigen und strategisch benachteiligten osmanischen Armeen und erzielten rasche Erfolge'},
                        {'Names': 'Der österreichische Thronfolger Franz Ferdinand wird ermordet',
                        'Dates': '28. Juni 1914',
                        'Explain': 'Die Ermittlungen ergaben, dass der serbische Geheimdienst die Verschwörer unterstützt hat. Damit hat Österreich-Ungarn entgültig einen Grund um gegen Serbien vorzugehen'},
                        {'Names': 'Die Anbringung der Inschrift "Dem deutschen Volke" am Giebel des deutschen Reichstags',
                        'Dates': '20. Dezember 1916',
                        'Explain': 'Es wurde von Johannes Kaempf 1915 in Auftrag gegeben, ca. 20 Jahre nach der Errichtung des eigentlichen Gebäutes'},
                        {'Names': 'Die Mikrowelle wird erfunden',
                        'Dates': 'Januar 1945',
                        'Explain': 'Percy LeBaron Spencer schmolz bei einem seiner Versuche mit Radarsystemen seine Schokolade. Dieses Ergebnis testete er später mit Popkorn, wodurch schließlich die Mikrowelle entsteht'},
                        {'Names': 'Der erste Satellit wird ins All geschossen',
                        'Dates': '4. Oktober 1957',
                        'Explain': 'Der Name des sowjetischen Satelliten ist Sputnik 1. Damit zeigt die UdSSR ihre Überlegenheit in der Raumfahrt und löst in der westlichen Welt einen Schock aus'},
                        {'Names': 'Der erste Mensch landet auf dem Mond',
                        'Dates': '21. Juli 1969',
                        'Explain': 'Niel Armstrong und Buzz Aldrin setzen das erste Mal einen Schritt auf den Mond. Währenddessen bleibt Michael Collins als Pilot im Kommandomodul. Die Apollo 11 Mission dauert ganze 8 Tage'},
                        {'Names': 'Die chinesische Regierung löst friedliche Studentenproteste auf',
                        'Dates': '4. Juni 1989', 
                        'Explain': "Auch China weiß nicht mehr was am Tian'anmen Square eigentlich passiert ist. Zufälligerweise war in der Nähe eine Militärparade",
                        'Explain2': 'In den 1980er Jahren hatte die chinesische Regierung einige Veränderungen. Sie erlaubten mehr private Firmen und auserländliche Investments. Demnach gab es auch Hoffnung für mehr politische Offenheit der Regierung. Die kommunistische Partei war gespalten unter denen, die sich mehr Offenheit wünschten, und denen, die staatliche Kontrolle wollten' + '<br>' + '-' + '<br>' + 'Das ausschlaggebende Ereignis war der Tod von Hu Yaobang, einer der führenden Politiker, der eine Änderung Chinas zur Offenheit wollte. Dieser wurde 2 Jahre vorher von politischen Gegnern aus der Partei gedrängt.' + '<br>' + '-' + '<br>' + 'Durch seinen Tod lebte die Protestbewegung wieder auf. Viele waren für mehr Freiheit der Bürger und weniger staatliche Zensur. In den nächsten Wochen sammelten sich die Protestanten, bis zu eine Millionen auf einmal, am Tiananmen Square, der "Platz am Tor des himmlischen Friedens". Anfangs wollte die Regierung noch nicht dagegen vorgehen. Andere wollten härtere Maßnahmen dagegen. Die, die für härtere Maßnahmen waren, haben die Debatte gewonnen. In den letzten 2 Maiwochen wurde das Kriegsrecht durchgesetzt.' + '<br>' + '-' + '<br>' + 'Vom 3. bis 4. Mai marschierten bewaffnete Truppen, unter anderem mit Panzern, zum Tiananmen Square und eröffneten das Feuer. Niemand weiß genau wie viele an dem Tag gestorben sind. Am nächsten Tag, als die Panzer abziehten, trat ein Mann mit zwei Einkaufstüten auf offener Straße den Panzern entgegen. Er wurde letzten Endes von anderen weggezogen. Er gilt als die Ikone des "Tiananmen Square Massakers".' + '<br>' + '-' + '<br>' + 'Bis heute noch zensiert die chinesische Regierung sämtliche Infos über das Massaker aus dem chinesischen Internet. Sie versuchen das Ereignis zu begraben und behaupten auch, das dort nur eine Militärparade war. Viele junge Leute in China wissen demanch nichts von dem Ereignis.'}]